CREATE TABLE Customer (
    `client_id` VARCHAR(8),
    `Name` VARCHAR(21),
    `Age` INT,
    `Location_ID` INT,
    `Joined_Bank` VARCHAR(10),
    `Banking_Contact` VARCHAR(19),
    `Nationality` VARCHAR(10),
    `Occupation` VARCHAR(36),
    `Fee_Structure` VARCHAR(4),
    `Loyalty_Classification` VARCHAR(8),
    `Estimated_Income` DOUBLE,
    `Superannuation_Savings` DOUBLE,
    `Amount_of_Credit_Cards` INT,
    `Credit_Card_Balance` DOUBLE,
    `Bank_Loans` DOUBLE,
    `Bank_Deposits` DOUBLE,
    `Checking_Accounts` DOUBLE,
    `Saving_Accounts` DOUBLE,
    `Foreign_Currency_Account` DOUBLE,
    `Business_Lending` DOUBLE,
    `Properties_Owned` INT,
    `Risk_Weighting` INT,
    `BRId` INT,
    `GenderId` INT,
    `IAId` INT
);
